abb_irb:
  robot_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

    gains: # Required because we're controlling an effort interface
      joint_1: {p: 10000.0, i: 0.01, d: 1000.0}
      joint_2: {p: 10000.0, i: 0.01, d: 1000.0}
      joint_3: {p: 10000.0, i: 0.01, d: 1000.0}
      joint_4: {p: 10000.0, i: 0.01, d: 1000.0}
      joint_5: {p: 10000.0, i: 0.01, d: 1000.0}
      joint_6: {p: 10000.0, i: 0.01, d: 1000.0}

    state_publish_rate:  100            # Override default
    action_monitor_rate: 100            # Override default
    stop_trajectory_duration: 0        # Override default